[package]
name = "alumy-linux"
version.workspace = true
edition.workspace = true
authors.workspace = true
description = "Linux integrations for the alumy cross-platform SDK."
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
readme.workspace = true
keywords = ["cross-platform", "sdk", "utilities", "logging", "filesystem"]
categories = ["development-tools", "os"]
rust-version.workspace = true

[dependencies]
alumy-core = { workspace = true, features = ["alloc"] }
anyhow.workspace = true
crossbeam.workspace = true
libc.workspace = true
rolling-file.workspace = true
time.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[features]
default = []

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
