[package]
name = "alumy-example-freertos"
version.workspace = true
edition.workspace = true
publish = false
rust-version.workspace = true

[dependencies]
alumy = { path = "../..", default-features = false, features = ["freertos"] }

[target.'cfg(target_arch = "arm")'.dependencies]
freertos-rust = "0.2"
cortex-m = "=0.7.7"
cortex-m-rt = "=0.7.3"
panic-halt = "=0.2.0"

[build-dependencies]
freertos-cargo-build = "0.2"
