[package]
name = "alumy-example-embassy"
version.workspace = true
edition.workspace = true
publish = false
rust-version.workspace = true

[dependencies]
alumy = { path = "../..", default-features = false, features = ["embassy"] }
embassy-executor = { version = "=0.6.3", features = ["arch-cortex-m", "executor-thread"] }
embassy-time = "=0.3.2"
cortex-m = "=0.7.7"
cortex-m-rt = "=0.7.3"
panic-halt = "=0.2.0"
