[package]
name = "alumy-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
description = "Core no_std-friendly utilities for the alumy cross-platform SDK."
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
readme.workspace = true
keywords = ["cross-platform", "sdk", "utilities", "no-std"]
categories = ["development-tools", "no-std"]
rust-version.workspace = true

[dependencies]

[features]
default = ["alloc"]
alloc = []

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
